# Generated by Django 5.2.8 on 2025-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food'), ('Health', 'Health'), ('Business', 'Business'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=100)),
                ('featureImage', models.ImageField(default='default.png', upload_to='images/')),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=256)),
            ],
        ),
    ]
