# Generated by Django 5.2.8 on 2025-12-11 06:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food'), ('Health', 'Health'), ('Business', 'Business'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=100)),
                ('featureImage', models.ImageField(default='default.png', upload_to='images/')),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=256)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
