# Generated by Django 5.2.8 on 2025-12-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0004_blogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment')], max_length=10),
        ),
    ]
